%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 11-Feb-2024 22:25:32
                     ConfigInfos.Version = '9.14.0.2337262 (R2023a) Update 5';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\SGHOSH18\MATLAB\Projects\Dissertation_EV2M';
                    ConfigInfos.ProjPath = 'C:\Users\SGHOSH18\MATLAB\Projects\Dissertation_EV2M\VirtualVehicle\VirtualVehicle';
                 ConfigInfos.SessionName = 'ConfiguredVirtualVehicle';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplate';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModels';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
                    ConfigInfos.VehClass = 'PassengerCar';
                     ConfigInfos.VehArct = 'Electric Vehicle 2EM';
                      ConfigInfos.VehDyn = 1;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 6DOF Longitudinal and Lateral';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Chassis') = 'Vehicle Body 6DOF Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'DC-DC Converter';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'Two Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Predictive Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'All Wheel Driven by 2EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM';
ConfigInfos.FeatureVariantSelectedMap('Electric Motor') = '2EM';
ConfigInfos.FeatureVariantSelectedMap('Electrical System') = 'Electrical System';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 2EM)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Standard Ambient';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Solver Configuration') = 'Solver Configuration';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'Kinematic Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension') = 'Kinematics and Compliance Independent Suspension';
ConfigInfos.FeatureVariantSelectedMap('Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Ideal Fixed Gear Transmission';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'Multi Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 2EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 2EM';

%% Test Plan

             ConfigInfos.TestPlan{1}.Num = 1;
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Increasing Steer';
           ConfigInfos.TestPlan{1}.Cycle = 'Disabled';
        ConfigInfos.TestPlan{1}.Data=[];

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattSoc',...
'Battery.BattVolt',...
'Battery.BattCurr',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Driver.SteerFdbk',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'Driveline.EMSpd',...
'EM.EMTrq',...
};

%% Imported Data Sources

%% Finish
